/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.IBilgiController;
import database.transactions.HesapBilgileri;
import database.transactions.KullaniciBasvuru;
import gui.ayarlar.ActionAyarlar;
import gui.ayarlar.ButtonAyarlar;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDüzenleyici;
import gui.ayarlar.TextAyarlar;
import java.awt.Color;

/**
 *
 * @author GÜRKAN ŞAHİN
 */
public final class BasvuruEkrani extends javax.swing.JFrame implements IDüzenleyici,IBilgiController{

    private  KullaniciBasvuru kullanicibasvuruObject=null;
    public BasvuruEkrani() {
        initComponents();
        getEdits();
        
        
        
    }

    @Override
    public void getEdits() { 
        this.setLocationRelativeTo(null);
        BasvuruEkraniPanel.setFocusable(true);
        TextAyarlar.setOnlyAlphabetic(AdSoyadText);
        TextAyarlar.setOnlyNumber(TcnoText);
        TextAyarlar.setmaxlimit(TcnoText, 11);
        TextAyarlar.setOnlyNumber(TelefonnoText);
        TextAyarlar.setmaxlimit(TelefonnoText, 11);
        
    }

    public KullaniciBasvuru getKullanicibasvuruObject() {
        
        if (this.kullanicibasvuruObject==null) {
            
            kullanicibasvuruObject=new KullaniciBasvuru();
        }
        return kullanicibasvuruObject;
    }

    @Override
    public boolean bilgilerGeçerlimi() {

        return TextAyarlar.textAlanlariDolumu(BasvuruEkraniPanel);
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return  HesapBilgileri.getInstance();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasvuruEkraniPanel = new javax.swing.JPanel();
        kisiselbilgilerLabel = new javax.swing.JLabel();
        AdsoyadLabel = new javax.swing.JLabel();
        AdSoyadText = new javax.swing.JTextField();
        TcnoLabel = new javax.swing.JLabel();
        TcnoText = new javax.swing.JTextField();
        TelefonnoText = new javax.swing.JTextField();
        TelefonNoLabel = new javax.swing.JLabel();
        güvenlikbilgileriLabel = new javax.swing.JLabel();
        güvenlikSorusuLabel = new javax.swing.JLabel();
        güvenliksorusuCb = new javax.swing.JComboBox<>();
        guvenlikcevapLabel = new javax.swing.JLabel();
        guvenlikcevapText = new javax.swing.JTextField();
        basvurButton = new javax.swing.JButton();
        cikislabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atm Bankası Başvuru Ekranı");
        setMinimumSize(new java.awt.Dimension(730, 660));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BasvuruEkraniPanel.setBackground(new java.awt.Color(0, 204, 204));
        BasvuruEkraniPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kisiselbilgilerLabel.setFont(new java.awt.Font("Tahoma", 3, 34)); // NOI18N
        kisiselbilgilerLabel.setForeground(new java.awt.Color(51, 51, 51));
        kisiselbilgilerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kisiselbilgilerLabel.setText("Kişisel Bilgiler");
        BasvuruEkraniPanel.add(kisiselbilgilerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 270, -1));

        AdsoyadLabel.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        AdsoyadLabel.setForeground(new java.awt.Color(51, 51, 51));
        AdsoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AdsoyadLabel.setText("Ad Soyad");
        BasvuruEkraniPanel.add(AdsoyadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 160, 28));

        AdSoyadText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BasvuruEkraniPanel.add(AdSoyadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 160, 25));

        TcnoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        TcnoLabel.setForeground(new java.awt.Color(51, 51, 51));
        TcnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TcnoLabel.setText("T.C.No");
        BasvuruEkraniPanel.add(TcnoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 160, 20));

        TcnoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BasvuruEkraniPanel.add(TcnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 160, 25));

        TelefonnoText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BasvuruEkraniPanel.add(TelefonnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 160, 25));

        TelefonNoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        TelefonNoLabel.setForeground(new java.awt.Color(51, 51, 51));
        TelefonNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TelefonNoLabel.setText("Telefon");
        BasvuruEkraniPanel.add(TelefonNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 160, -1));

        güvenlikbilgileriLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        güvenlikbilgileriLabel.setForeground(new java.awt.Color(255, 255, 255));
        güvenlikbilgileriLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BasvuruEkraniPanel.add(güvenlikbilgileriLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, -1));

        güvenlikSorusuLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        güvenlikSorusuLabel.setForeground(new java.awt.Color(51, 51, 51));
        güvenlikSorusuLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        güvenlikSorusuLabel.setText("G.Sorusu");
        BasvuruEkraniPanel.add(güvenlikSorusuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 160, -1));

        güvenliksorusuCb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        güvenliksorusuCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evcil hayvanınızın adı?", "En sevdiğiniz nesne?", "İlkokulda en sevdiğiniz ders?", "Yaşamak İstediğiniz yer ?", "Ya da rastgele cümle girin(önerilen)" }));
        BasvuruEkraniPanel.add(güvenliksorusuCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 160, -1));

        guvenlikcevapLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        guvenlikcevapLabel.setForeground(new java.awt.Color(51, 51, 51));
        guvenlikcevapLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guvenlikcevapLabel.setText("Cevap");
        BasvuruEkraniPanel.add(guvenlikcevapLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 160, -1));

        guvenlikcevapText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BasvuruEkraniPanel.add(guvenlikcevapText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 160, -1));

        basvurButton.setBackground(new java.awt.Color(255, 255, 204));
        basvurButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        basvurButton.setText("Başvur");
        basvurButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basvurButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basvurButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basvurButtonMouseExited(evt);
            }
        });
        basvurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvurButtonActionPerformed(evt);
            }
        });
        BasvuruEkraniPanel.add(basvurButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 101, -1));

        cikislabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/previous.png"))); // NOI18N
        cikislabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikislabelMouseClicked(evt);
            }
        });
        BasvuruEkraniPanel.add(cikislabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/ATM-Machine.jpg"))); // NOI18N
        BasvuruEkraniPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 830, 870));

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        BasvuruEkraniPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 590, 30, 20));

        getContentPane().add(BasvuruEkraniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basvurButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseEntered
        ButtonAyarlar.setBg(basvurButton, Color.CYAN);
    }//GEN-LAST:event_basvurButtonMouseEntered

    private void basvurButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseExited
       ButtonAyarlar.setOriginalBg(basvurButton);
    }//GEN-LAST:event_basvurButtonMouseExited

    private void basvurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvurButtonActionPerformed
        if (this.bilgilerGeçerlimi()) {
            
            //ActionAyarlar.setVisible(this, new giris_ekrani());
            basvuruyugerceklestir();

        }
        else{
            
            Dialogs.bosOlamazMesajıGöster(this);
        }
        
        
    }//GEN-LAST:event_basvurButtonActionPerformed

    private void cikislabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikislabelMouseClicked

        ActionAyarlar.setVisible(this, new giris_ekrani());
    }//GEN-LAST:event_cikislabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          if (this.bilgilerGeçerlimi()) {
            
            //ActionAyarlar.setVisible(this, new giris_ekrani());
            basvuruyugerceklestir();

        }
        else{
            
            Dialogs.bosOlamazMesajıGöster(this);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private  void basvuruyugerceklestir(){
        //kullanıcı basşvuru sınıfından objemizi method yardmımı ile ürettik
        
        
        //Kişisel Bilgileri gönderiyoruz
        this.getKullanicibasvuruObject().setAdSoyad(this.AdSoyadText.getText().trim());
        this.getKullanicibasvuruObject().setTcNo(this.TcnoText.getText());
        this.getKullanicibasvuruObject().setTelNo(this.TelefonnoText.getText());
        
        //Güvenlik Bilgileri
         this.getKullanicibasvuruObject().setGuvenliksorusu( String.valueOf(this.güvenliksorusuCb.getSelectedItem()));
         this.getKullanicibasvuruObject().setGuvenlikcevap(this.guvenlikcevapText.getText().trim());
         
         //Sistem Tarafından verilecek bilgiler
          this.getKullanicibasvuruObject().setMusteriNo(this.randomMusteriNoAl());
          this.getKullanicibasvuruObject().setSifre(this.randomSifreAl());

         
           if (this.getKullanicibasvuruObject().basvuruonaylandimi()) {
            Dialogs.OzelMesajGöster(this, "Başvurunuz kabul edilmiştir. \n"
                    + "Müşteri Numaranız:"+this.getKullanicibasvuruObject().getMusteriNo()
                    +"\nŞifreniz:"+this.getKullanicibasvuruObject().getSifre());
            ActionAyarlar.setVisible(this, new giris_ekrani());
        }
           else{
               
               Dialogs.OzelMesajGöster(this,"Başvurunuz kabul edilmemiştir. \n"
                       + "Lütfen bilgilerinizi kontrol edin.");
           }
        
        
        
        
    }
    
    public String randomMusteriNoAl(){
        String MusteriNo;
         do {
           MusteriNo=String.valueOf(1000000+(int)(Math.random()* 9000000));
         } while(this.getKullanicibasvuruObject().musterinotablodavar_mi());
        return  MusteriNo;
        
    }
    
     public String randomSifreAl(){
        String sifre;
        sifre=String.valueOf(1000+(int)(Math.random()* 9000));
        return sifre;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasvuruEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdSoyadText;
    private javax.swing.JLabel AdsoyadLabel;
    private javax.swing.JPanel BasvuruEkraniPanel;
    private javax.swing.JLabel TcnoLabel;
    private javax.swing.JTextField TcnoText;
    private javax.swing.JLabel TelefonNoLabel;
    private javax.swing.JTextField TelefonnoText;
    private javax.swing.JButton basvurButton;
    private javax.swing.JLabel cikislabel;
    private javax.swing.JLabel guvenlikcevapLabel;
    private javax.swing.JTextField guvenlikcevapText;
    private javax.swing.JLabel güvenlikSorusuLabel;
    private javax.swing.JLabel güvenlikbilgileriLabel;
    private javax.swing.JComboBox<String> güvenliksorusuCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kisiselbilgilerLabel;
    // End of variables declaration//GEN-END:variables
}
