/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.DbConnection;
import database.IBilgiController;
import database.transactions.HesapBilgileri;
import database.transactions.Kullanici_Giris;
import gui.ayarlar.ActionAyarlar;
import gui.ayarlar.ButtonAyarlar;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDüzenleyici;
import gui.ayarlar.TextAyarlar;
import java.awt.Color;

/**
 *
 * @author GÜRKAN ŞAHİN
 */
public final class giris_ekrani extends javax.swing.JFrame implements IDüzenleyici,IBilgiController {
    
    private  Kullanici_Giris kullanici_giris_object=null;
    
    private final  String kimlik_text_orginal="T.C. No / Müşteri No";
    private final  String sifre_text_orginal="**********";

    /**
     * Creates new form giris_ekrani
     */
    public giris_ekrani() {
        initComponents();
        getEdits();
      
        new DbConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        girisEkraniPanel = new javax.swing.JPanel();
        hosgeldinizLabel = new javax.swing.JLabel();
        kimlikText = new javax.swing.JTextField();
        sifreText = new javax.swing.JPasswordField();
        girisButton = new javax.swing.JButton();
        soruLabel = new javax.swing.JLabel();
        basvurButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Ekranı");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        girisEkraniPanel.setBackground(new java.awt.Color(0, 204, 204));
        girisEkraniPanel.setLayout(null);

        hosgeldinizLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        hosgeldinizLabel.setForeground(new java.awt.Color(102, 102, 102));
        hosgeldinizLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hosgeldinizLabel.setText("ATM BANKAYA  HOŞGELDİNİZ");
        girisEkraniPanel.add(hosgeldinizLabel);
        hosgeldinizLabel.setBounds(200, 420, 375, 50);

        kimlikText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kimlikText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kimlikTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kimlikTextFocusLost(evt);
            }
        });
        girisEkraniPanel.add(kimlikText);
        kimlikText.setBounds(280, 470, 210, 30);

        sifreText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sifreText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sifreTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sifreTextFocusLost(evt);
            }
        });
        sifreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreTextActionPerformed(evt);
            }
        });
        girisEkraniPanel.add(sifreText);
        sifreText.setBounds(280, 520, 210, 30);

        girisButton.setBackground(new java.awt.Color(255, 255, 204));
        girisButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        girisButton.setForeground(new java.awt.Color(51, 51, 51));
        girisButton.setText("Giriş");
        girisButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        girisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                girisButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                girisButtonMouseExited(evt);
            }
        });
        girisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButtonActionPerformed(evt);
            }
        });
        girisEkraniPanel.add(girisButton);
        girisButton.setBounds(260, 590, 101, 30);

        soruLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        soruLabel.setForeground(new java.awt.Color(255, 255, 255));
        girisEkraniPanel.add(soruLabel);
        soruLabel.setBounds(330, 420, 150, 0);

        basvurButton.setBackground(new java.awt.Color(255, 255, 204));
        basvurButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        basvurButton.setForeground(new java.awt.Color(51, 51, 51));
        basvurButton.setText("Kaydol");
        basvurButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basvurButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basvurButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basvurButtonMouseExited(evt);
            }
        });
        basvurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basvurButtonActionPerformed(evt);
            }
        });
        girisEkraniPanel.add(basvurButton);
        basvurButton.setBounds(390, 590, 101, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Şifreni mi unuttun?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        girisEkraniPanel.add(jLabel1);
        jLabel1.setBounds(340, 560, 111, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/ATM-Machine.jpg"))); // NOI18N
        girisEkraniPanel.add(jLabel3);
        jLabel3.setBounds(-10, 0, 890, 880);

        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        girisEkraniPanel.add(jLabel4);
        jLabel4.setBounds(530, 600, 38, 16);

        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        girisEkraniPanel.add(jLabel5);
        jLabel5.setBounds(220, 600, 38, 20);

        getContentPane().add(girisEkraniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 800));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //İnterfce içindeki methodumuzu çağırdık
    @Override
    public void getEdits() {    
        
        this.setLocationRelativeTo(this);
        girisEkraniPanel.setFocusable(true);
        kimlikText.setText(kimlik_text_orginal);
        sifreText.setText(sifre_text_orginal);
        TextAyarlar.setOnlyNumber(kimlikText);
    }

    @Override
   public boolean bilgilerGeçerlimi() {
    return !(this.kimlikText.getText().equals(this.kimlik_text_orginal)
            && String.valueOf(this.sifreText.getPassword()).equals(this.sifre_text_orginal));
}


    @Override
    public HesapBilgileri getHesapBilgileri() {
        return  HesapBilgileri.getInstance();
    }

    public Kullanici_Giris getKullanici_giris_object() {
       
        if (this.kullanici_giris_object == null) {
            
            kullanici_giris_object=new Kullanici_Giris();
        }
        return kullanici_giris_object;
    }
    
    

    
    private void sifreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreTextActionPerformed

    private void basvurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basvurButtonActionPerformed

        
        //giriş ekranını kapatmış oluyoruz
        ActionAyarlar.setVisible(this, new BasvuruEkrani());
    }//GEN-LAST:event_basvurButtonActionPerformed

    //BUTTON RENKLENDİRMELERİ VE HOVER ÖZELLİKLERİ
    private void girisButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisButtonMouseEntered

        ButtonAyarlar.setBg(girisButton, Color.CYAN);
    }//GEN-LAST:event_girisButtonMouseEntered


    private void girisButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisButtonMouseExited
        // TODO add your handling code here:
      ButtonAyarlar.setOriginalBg(girisButton);
    }//GEN-LAST:event_girisButtonMouseExited

    private void basvurButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseEntered
        // TODO add your handling code here:
  ButtonAyarlar.setBg(basvurButton, Color.CYAN);
    }//GEN-LAST:event_basvurButtonMouseEntered

    private void basvurButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basvurButtonMouseExited
        // TODO add your handling code here:
  ButtonAyarlar.setOriginalBg(basvurButton);
    }//GEN-LAST:event_basvurButtonMouseExited

    
    //TEXT AYARLARI
    private void kimlikTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kimlikTextFocusGained
        
      TextAyarlar.ChecktheTextFocusGained(kimlikText, kimlik_text_orginal);
    }//GEN-LAST:event_kimlikTextFocusGained

    private void kimlikTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kimlikTextFocusLost
        TextAyarlar.ChecktheTextFocusLost(kimlikText);
    }//GEN-LAST:event_kimlikTextFocusLost

    private void sifreTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreTextFocusGained
       TextAyarlar.ChecktheTextFocusGained(sifreText, sifre_text_orginal);
    }//GEN-LAST:event_sifreTextFocusGained

    private void sifreTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreTextFocusLost
     TextAyarlar.ChecktheTextFocusLost(sifreText);
    }//GEN-LAST:event_sifreTextFocusLost

    private void girisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButtonActionPerformed
           if (this.bilgilerGeçerlimi()) {
            String Musteri_Kimlik=this.kimlikText.getText().trim();
            String Sifre=String.valueOf(this.sifreText.getPassword());
            this.girisyap(Musteri_Kimlik,Sifre);
        }
           else {
               Dialogs.bosOlamazMesajıGöster(this);
           }
    }//GEN-LAST:event_girisButtonActionPerformed

    private  void girisyap(String musteriKimlik,String sifre){
        
        this.getKullanici_giris_object().setMusteriKimlik(musteriKimlik);
        this.getKullanici_giris_object().setSifre(sifre);
        
        if (getKullanici_giris_object().girisBilgileriDogruMu()) {
            
            ActionAyarlar.setVisible(this, new HesapEkrani());
        }
        else{
            Dialogs.OzelMesajGöster(this, "Giriş bilgileri doğru değildir!\n"
                    + "Lütfen bilgilerinizi kontrol ediniz!");
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

      
          ActionAyarlar.setVisible(this, new SifreYenilemeEkrani());
      
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ActionAyarlar.setVisible(this, new BasvuruEkrani());    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
  if (this.bilgilerGeçerlimi()) {
            String Musteri_Kimlik=this.kimlikText.getText().trim();
            String Sifre=String.valueOf(this.sifreText.getPassword());
            this.girisyap(Musteri_Kimlik,Sifre);
        }
           else {
               Dialogs.bosOlamazMesajıGöster(this);
           }    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basvurButton;
    private javax.swing.JButton girisButton;
    private javax.swing.JPanel girisEkraniPanel;
    private javax.swing.JLabel hosgeldinizLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kimlikText;
    private javax.swing.JPasswordField sifreText;
    private javax.swing.JLabel soruLabel;
    // End of variables declaration//GEN-END:variables
}
