/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.IBilgiController;
import database.transactions.HesapBilgileri;
import database.transactions.ParaCekme;
import gui.ayarlar.ActionAyarlar;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDüzenleyici;
import gui.ayarlar.TextAyarlar;

/**
 *
 * @author GÜRKAN ŞAHİN
 */
public class ParaCekmeEkrani extends javax.swing.JFrame implements IDüzenleyici ,IBilgiController{

    private ParaCekme paracekmeObject = getParacekmeObject();
    
    private  int cekilecekmiktar=0;
    
    public ParaCekmeEkrani() {
        initComponents();
        getEdits(); 
    }

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        TextAyarlar.setOnlyNumber(cekilecekmiktarText);
        TextAyarlar.setmaxlimit(cekilecekmiktarText, 4);
        this.KullaniciAdiSoyadiLabel.setText("Sayın " + this.getHesapBilgileri().getAdSoyad());
        this.BakiyeLabel.setText(String.valueOf(this.getHesapBilgileri().getBakiye()));
    }

    @Override
    public boolean bilgilerGeçerlimi() {
       return !(this.cekilecekmiktarText.getText().equals(""));
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return HesapBilgileri.getInstance();
    }

    
    
    public ParaCekme getParacekmeObject() {
        
        if (this.paracekmeObject == null) {
            paracekmeObject=new ParaCekme();
        }
        return paracekmeObject;
    }
    
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParaCekmeEkraniPanel = new javax.swing.JPanel();
        KullaniciAdiSoyadiLabel = new javax.swing.JLabel();
        limituyariLabel = new javax.swing.JLabel();
        toplamBakiyenizLabel = new javax.swing.JLabel();
        BakiyeLabel = new javax.swing.JLabel();
        cekeceginizmiktarLabel = new javax.swing.JLabel();
        cekilecekmiktarText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ParaCekButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        paracekmelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParaCekmeEkraniPanel.setBackground(new java.awt.Color(204, 255, 204));
        ParaCekmeEkraniPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KullaniciAdiSoyadiLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        KullaniciAdiSoyadiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KullaniciAdiSoyadiLabel.setText("Sayın [Kullanıcı_Adi_Soyadi]");
        ParaCekmeEkraniPanel.add(KullaniciAdiSoyadiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 330, 40));

        limituyariLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        limituyariLabel.setForeground(new java.awt.Color(255, 0, 51));
        limituyariLabel.setText("Tek seferde 7000 TL ve altını çekebilirsiniz!");
        ParaCekmeEkraniPanel.add(limituyariLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 326, 32));

        toplamBakiyenizLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toplamBakiyenizLabel.setForeground(new java.awt.Color(51, 51, 51));
        toplamBakiyenizLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        toplamBakiyenizLabel.setText("Toplam Bakiyeniz:");
        ParaCekmeEkraniPanel.add(toplamBakiyenizLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 197, 32));

        BakiyeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BakiyeLabel.setForeground(new java.awt.Color(51, 51, 51));
        BakiyeLabel.setText("[Bakiye]");
        ParaCekmeEkraniPanel.add(BakiyeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 226, 32));

        cekeceginizmiktarLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cekeceginizmiktarLabel.setForeground(new java.awt.Color(51, 51, 51));
        cekeceginizmiktarLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cekeceginizmiktarLabel.setText("Çekeceğiniz Miktar");
        ParaCekmeEkraniPanel.add(cekeceginizmiktarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, 32));

        cekilecekmiktarText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cekilecekmiktarText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cekilecekmiktarTextKeyReleased(evt);
            }
        });
        ParaCekmeEkraniPanel.add(cekilecekmiktarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/previous.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        ParaCekmeEkraniPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 47, 51));

        ParaCekButton1.setBackground(new java.awt.Color(51, 51, 51));
        ParaCekButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ParaCekButton1.setForeground(new java.awt.Color(255, 255, 255));
        ParaCekButton1.setText("Para Çek");
        ParaCekButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParaCekButton1MouseClicked(evt);
            }
        });
        ParaCekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParaCekButton1ActionPerformed(evt);
            }
        });
        ParaCekmeEkraniPanel.add(ParaCekButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 545, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/ATM-Machine.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        ParaCekmeEkraniPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 790, 820));

        paracekmelabel.setText("jLabel3");
        paracekmelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paracekmelabelMouseClicked(evt);
            }
        });
        ParaCekmeEkraniPanel.add(paracekmelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 20, 20));

        getContentPane().add(ParaCekmeEkraniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekilecekmiktarTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cekilecekmiktarTextKeyReleased

        this.cekilecekmiktar= TextAyarlar.CheckTextKeyReleased(cekilecekmiktarText, 7000);
    }//GEN-LAST:event_cekilecekmiktarTextKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        ActionAyarlar.setVisible(this, new HesapEkrani());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ParaCekButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParaCekButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ParaCekButton1MouseClicked

    private void ParaCekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParaCekButton1ActionPerformed
           if (this.bilgilerGeçerlimi()) {
            this.paracek();
        }else{
            Dialogs.bosOlamazMesajıGöster(this);
        }
    }//GEN-LAST:event_ParaCekButton1ActionPerformed

    private void paracekmelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paracekmelabelMouseClicked
  if (this.bilgilerGeçerlimi()) {
            this.paracek();
        }else{
            Dialogs.bosOlamazMesajıGöster(this);
        }    }//GEN-LAST:event_paracekmelabelMouseClicked

    
    
    
    private void paracek(){

        this.paracekmeObject.setCekilecekmiktar(cekilecekmiktar);
        
        if (getParacekmeObject().ParaCekildiMi()) {
            Dialogs.OzelMesajGöster(this, "Para cekme işlemi tamamlandı\n"
                    + "Çekilen Miktar: "  +  this.cekilecekmiktar  + " TL");
            
                ActionAyarlar.setVisible(this, new HesapEkrani());
        }
        else{
            Dialogs.OzelMesajGöster(this, "Yetersiz Bakiye!.");
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaCekmeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaCekmeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BakiyeLabel;
    private javax.swing.JLabel KullaniciAdiSoyadiLabel;
    private javax.swing.JButton ParaCekButton1;
    private javax.swing.JPanel ParaCekmeEkraniPanel;
    private javax.swing.JLabel cekeceginizmiktarLabel;
    private javax.swing.JTextField cekilecekmiktarText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel limituyariLabel;
    private javax.swing.JLabel paracekmelabel;
    private javax.swing.JLabel toplamBakiyenizLabel;
    // End of variables declaration//GEN-END:variables
}
